{
	"version": 1600061291,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/bullet-sheet0.png",
		"images/enemy-sheet0.png",
		"images/enemy-sheet1.png",
		"images/enemy-sheet2.png",
		"images/enemybullet-sheet0.png",
		"images/star-sheet0.png",
		"images/bg_mundo1-sheet0.png",
		"images/explosion-sheet0.png",
		"images/hud_1-sheet0.png",
		"images/barra1-sheet0.png",
		"images/hud_2-sheet0.png",
		"images/spfonthud_aliens.png",
		"images/barra2-sheet0.png",
		"images/hud_3-sheet0.png",
		"images/barra3-sheet0.png",
		"images/bt_cerrar-sheet0.png",
		"images/coin-sheet0.png",
		"images/coin-sheet1.png",
		"images/fuego-sheet0.png",
		"images/boom_nave-sheet0.png",
		"images/boom_nave-sheet1.png",
		"images/game_over-sheet0.png",
		"images/bt_go-sheet0.png",
		"images/tbg_fade.png",
		"images/boom_verde-sheet0.png",
		"images/boom_verde-sheet1.png",
		"images/bg_portada-sheet0.png",
		"images/bt_play-sheet0.png",
		"images/logo-sheet0.png",
		"images/energy_pack-sheet0.png",
		"images/logo_genius-sheet0.png",
		"images/planeta1-sheet0.png",
		"images/comic1-sheet0.png",
		"images/comic1-sheet1.png",
		"images/bt_seguir-sheet0.png",
		"images/tiledbackground.png",
		"images/tbg_gris.png",
		"images/coming_soon-sheet0.png",
		"media/flaunch.m4a",
		"media/flaunch.ogg",
		"media/bip missile.m4a",
		"media/bip missile.ogg",
		"media/slimeball.m4a",
		"media/slimeball.ogg",
		"media/explosion.ogg",
		"media/fx093.m4a",
		"media/fx093.ogg",
		"media/fx099.m4a",
		"media/fx099.ogg",
		"media/fx096.m4a",
		"media/fx096.ogg",
		"media/disparo1.m4a",
		"media/disparo1.ogg",
		"media/fx098.m4a",
		"media/fx098.ogg",
		"media/game over voice.m4a",
		"media/game over voice.ogg",
		"media/fx097.m4a",
		"media/fx097.ogg",
		"media/well done_01.m4a",
		"media/well done_01.ogg",
		"media/irrational machines - rpg title screen music pack - 01 title screen.m4a",
		"media/irrational machines - rpg title screen music pack - 01 title screen.ogg",
		"media/juhani junkala [retro game music pack] title screen.m4a",
		"media/juhani junkala [retro game music pack] title screen.ogg",
		"media/intro heroico_01.m4a",
		"media/intro heroico_01.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}